### ISSUE TITLE
The server is not starting

### ISSUE THREAD

**Issue by RedstoneFX** [TastyLollipop/OpenWorld#1]
Maybe I'm doing something wrong, but the server won't start. Dot Net 6.0.2 is installed. The game is without mods. 
![image](https://user-images.githubusercontent.com/75026529/155987869-c7749476-03cc-435e-b682-8e1b869be079.png)
_Good luck with the development. I will be happy to send a donation in the future._
_(I use a translator.)_

**Comment by ghost** [comment]
Oh! You are not doing anything wrong. I forgot to change paths to check for files at the local folder of the program. Will upload a new fix asap. Thanks.

**Comment by ghost** [comment]
Should be fixed in the newest release. I'll leave this issue open in case it's still not working.

**Comment by Vomiri** [comment]
The same error as on the first screen, looking
 for files on drive D (which does not exist) and closes
 
 
![image](https://user-images.githubusercontent.com/99396117/156394747-a64d9ee5-3198-468d-adad-c8a7c1bc77e6.png)

**Comment by ghost** [comment]
Hm, weird. Can you post a screenshot of how the server folder looks? Thanks

**Comment by ghost** [comment]
Also, if you can, a photo of the server settings.txt and world settings.txt files to check for errors

**Comment by RedstoneFX** [comment]
My server folder unpacked from the latest release. The problem persists.

**Comment by TastyLollipop** [comment]
Please attach a photo of your server folder, settings.txt and world settings.txt

**Comment by ghost** [comment]
Alright forget all that. It was certainly an issue with system local culture. Now the new server version SHOULD totally work, 1.1.4. 

I'm sorry for all the trouble.

**Comment by RedstoneFX** [comment]
OK. I checked. Everything works. Thanks.
