### ISSUE TITLE
Gift done between [P1] and [P2] but was offline. Saving...

### ISSUE THREAD

**Issue by Sharingisnotillegal** [TastyLollipop/OpenWorld#11]
![image](https://user-images.githubusercontent.com/10707545/158499426-91acd8e0-67b1-4568-95a5-5732e045e007.png)
Incorrectly shows "Connected" on client, even if it is disconnected.  

Have not been able to consistently reproduce. Could be related to issue Trade failure #10 

https://gist.github.com/c6327351a081aa18a643f111d67a2190 This is log after having quit to menu, and joined back. Trading went through only after reconnect.

**Comment by Sharingisnotillegal** [comment]
Occurred again: Console shows:
Connected players 2, doublechecked both clients showed connected
2:33:02 Gift done between [p1] and p2] but was offline. Saving
2:34:42 Gift done between  [p1] and [p2]
2:35:19 Gift done between  [p1] and [p2]
3:49:51 Gift done between  [p1] and [p2]
3:50:20 Client [p2] disconnected
3:50:49 Client [p2] connected (restarted no items received)

Trading did not go through this time.

**Comment by ghost** [comment]
Hello. This error might have been fixed in latest version, named "Half Pawn!". Could you please try getting the latest update and trying again?
