### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Laser411** [TastyLollipop/OpenWorld#12]
Receiving the following error when attempting to start:

`
/home/cap/Rimworld/OpenWorldServer/Open\ World\ Server
Failed to load /snap/dotnet-sdk/158/shared/Microsoft.NETCore.App/6.0.3/libcoreclr.so, error: /snap/core18/current/lib/x86_64-linux-gnu/librt.so.1: undefined symbol: __clock_nanosleep, version GLIBC_PRIVATE
Segmentation fault (core dumped)
`
This is on a fresh and updated Ubuntu 20.04 install on a bhyve VM hosted on TrueNas.

**Comment by ghost** [comment]
Hello there. I believe this is no error with the server itself, but the way you are calling the executable.

Do you have the dependency .Net installed? If so, try calling the program directly from It. If not, please do install It as It's needed for the server to run.

**Comment by Laser411** [comment]
Calling the .dll with dotnet works, everything else does not.
