### ISSUE TITLE
Quest to player settlement can't deliver goods

### ISSUE THREAD

**Issue by Sharingisnotillegal** [TastyLollipop/OpenWorld#14]
Steps:
Accept quest (4 jacket normal+ quality) to "Player" settlement
Send Villager to player settlement
Button to complete quest does not exist
![RimWorldWin64_22-03-20_05-16_5M2P](https://user-images.githubusercontent.com/10707545/159151206-26bbde4b-c457-4fd8-b6ae-ee4309331e3d.png)
![image](https://user-images.githubusercontent.com/10707545/159151215-52fe31e4-f5c8-4fe6-b2fe-d76cffc40a18.png)

Logs
https://gist.github.com/HugsLibRecordKeeper/b3164bcdaf1cc62a85a1e8fe07ee3862

**Comment by ghost** [comment]
Are you using some kind of modded vehicle to travel around the map? If so, what's the mod name of that vehicle? Also, check that you are using latest server version 1.2.0, and mod version "Half Pawn!"

**Comment by Sharingisnotillegal** [comment]
> 
Hi,

I actually forgot to check if I was on Half Pawn when this occurred. But I can 100% confirm that server was 1.2.

No mods besides bare minumim required: 
Harmony
Core
HugsLib
Open World

I'll try again if I get a chance.

**Comment by Sharingisnotillegal** [comment]
Can confirm not working.  
1.2.3 server
Version secrecy  
Tried restarting game, verifying files.
Quest complete button is missing
Quest: Delivery 14 parka normal+ quality
https://gist.github.com/cfccd3c7262025f60d577809188f271a Log

![image](https://user-images.githubusercontent.com/10707545/160010151-dec754ac-9083-4528-9f18-52f89331f8d8.png)
Tried both connected, and loading without connecting.
![image](https://user-images.githubusercontent.com/10707545/160010330-7c8b8bf4-6b12-4931-a257-823ef6c143bb.png)

**Comment by LargoUsagi** [comment]
I can confirm reproduction of this bug, there is no way to complete the trade missions with player settlements from my experimentation with or without mods.

Version: v1.3.9

**Comment by ghost** [comment]
Finally found the bug! I'll be working to patch it on latest unstable version. Thanks for all the feedback!
