### ISSUE TITLE
You have been disconnected from server

### ISSUE THREAD

**Issue by Sharingisnotillegal** [TastyLollipop/OpenWorld#16]
Sorry, didn't read patchnotes clear enough.
"Max Players: 300" needs to be above your IP in server settings
"Please DO NOT just copy your previous server version's settings! just config the new one again, this function might not work otherwise!"

Open World Server v1.2.3 [Latest](https://github.com/TastyLollipop/OpenWorld/releases/latest)
https://gist.github.com/091faeea1b1d5980a3e7b198ce029b32
log

Just updated, can't connect anymore.
Reproduction steps:
Have 1.2 installed and running.
Connect OK.
exit 1.2
Move over .exe, .dll, and .json to same folder
start 1.2.3
Try connecting [load save menu, then connect button]

Server side error:
Player [Player1] Has disconnected
Player [Player2] Has disconnected

No further errors,
Happens immediately when pressing connect.

Can not view ingame version as i do not get connected.
Using workshop, tried verifying cache and reloading

**Comment by ghost** [comment]
Hello there, please send a photo of your server console, title included, when open (Feel free to cut out the IP should you want to). Also send "Server Settings.txt" that you  are using. Are you trying to modify your previous settings? Or generating/using the new one?

**Comment by Sharingisnotillegal** [comment]
Hi, correct. I added that to the first row. Just couldnt find how to close issue. :') Sorry!
