### ISSUE TITLE
LAN server Question 

### ISSUE THREAD

**Issue by NirronCD** [TastyLollipop/OpenWorld#2]
Is there any way you can make a LAN server, because my shitty ISP has a crap rule that blocks Port Fowarding.
EDIT: like with Radmin or Hamachi

**Comment by ghost** [comment]
Yes! Sorry for the delay! Things have been busy this days.

Yes, you can build a LAN server no problem, just make sure to use the local IP of the host's computer in the server settings. If you are playing on local you should be able to join no problem by using the same local IP, if it doesn't work try creating an exception for the server in the firewall!
