### ISSUE TITLE
All players must have DLC if DLC is enabled

### ISSUE THREAD

**Issue by KyamuDog** [TastyLollipop/OpenWorld#20]
If DLC is enabled in settings, all players must have the DLC as it is marked as a required mod.
I thought perhaps making a copy of the DLCs in the whitelist folder (and disabling the DLC in settings) might help to allow some of us to use the DLC while allowing others without the DLC to play on the server.

**Comment by ghost** [comment]
You are partially correct, yes. DLCs can be whitelisted if their folders are put in the "Whitelisted Mods" folder. They require a workaround to their files.

Here is a simpler solution: https://cdn.discordapp.com/attachments/951176474063413328/952959788168409098/DLCs.7z

Just put this in the folder and disable them in the settings, then all is good to go

**Comment by KyamuDog** [comment]
Thanks for the quick response!
