### ISSUE TITLE
Road spaghetti - bug or working as intended  

### ISSUE THREAD

**Issue by KyamuDog** [TastyLollipop/OpenWorld#21]
![image](https://user-images.githubusercontent.com/20000650/161898512-9848e361-64be-41fe-a7dd-00e65e971aab.png)
Are these persistent spaghetti roads to every colony (one of us fails a lot and has a lot of restarts) working as intended? Will the world one day devolve to Road?

**Comment by Sharingisnotillegal** [comment]
Have you tried generating the identical seed offline to see if it's identical?

**Comment by ghost** [comment]
Can confirm it's a bug for now. The game doesn't really know how to handle the roads for extra settlements, the function is disabled until I find how to fix it

**Comment by ghost** [comment]
Clossing this as the issue has been noticed and a solution is in the works. Will fix in later patch.

Thanks for reporting!
