### ISSUE TITLE
Cannot use Dynamic DNS URL as server address to connect

### ISSUE THREAD

**Issue by KyamuDog** [TastyLollipop/OpenWorld#23]
Using No-IP I have created a domain name that will be redirected to my IP to avoid disruptions when it changes as I do not have a static IP with my provider. 

Unfortunately using the domain name is not possible at present. It times out every time.

**Comment by KyamuDog** [comment]
It CAN be pinged, and will resolve to the IP address, but it will never connect

**Comment by Rythoka** [comment]
Sounds like a port forwarding issue to me. Did you also try connecting directly to the IP address the DynamicDNS resolves to?

**Comment by KyamuDog** [comment]
Decidedly not a port forwarding issue. The IP address works, and the URL resolves to the correct address when checked.
All of the players currently use the IP, but if a power outage occurs (or the IP expires) we get a new IP, which is why I am working on this.

**Comment by KyamuDog** [comment]
As it's closed source, I can't walk through it's connection process, but perhaps @TastyLollipop can shed some light on that. Is there perhaps some fuckery occurring when parsing an address that has subdomains? 
**example.ddns.net** as opposed to something more "normal" like **kyamudo.gg**
It's totally speculation, but it might be related to that, if it has to handle URLS and IP addresses differently (resolving the URL before connecting etc.) 

I could see a simple check for multiple '.' in the address field erroneously sending the URL to whatever code handles the direct IP connection or something rather that to the code responsible for resolving to an IP. 
I do of course make a lot of assumptions here.

**Comment by Rythoka** [comment]
I run a server that uses a subdomain with no issues whatsoever. Also, it's not difficult whatsoever to decompile the code if you're so inclined.

**Comment by KyamuDog** [comment]
Hmm... Not sure then. Like I said, the above was a shot in the dark.
Directly setting the A record on a domain I control allows others to
connect, but the ddns.net domains do not. Very strange.

All it does it update the A record of that subdomain every so often, so I'm
not sure what could be going wrong. On paper they ought to be identical.
