### ISSUE TITLE
Incompatibility with "Realistic Planets Continued"

### ISSUE THREAD

**Issue by totrider** [TastyLollipop/OpenWorld#24]
The multiplayer button gets replaced with a "back" button when Realistic Planets Continued is present: https://steamcommunity.com/sharedfiles/filedetails/?id=2557451791&searchtext=realistic+planet

**Comment by ghost** [comment]
Unfortunately this is an incompatibility that will be hard to fix if changes are not made to any of the two mod's map generation UI. Button overlapping is an iffy topic when talking about Rimworld.

Could you verify if you can work around this issue via changing the mod order of your game? Moving the "Open World" mod above or below "Realistic Planets Continued"

**Comment by haloTT100** [comment]
I recreated the issue.
RW Version:  1.3.3326
Mod load order:
1. Harmony
2. Core
3. Royalty
4. Ideology
5. HugsLib
6. Open World
7. Realistic Planets Continued

Missing multiplayer button when starting new game. Load game has the mp button. The game doesn't report any error in the console. **Changing the load order doesn't fix the issue.**
