### ISSUE TITLE
Client does not do anything after clicking join

### ISSUE THREAD

**Issue by Crockan** [TastyLollipop/OpenWorld#26]
So when my game client clicked join, the "multiplayer menu" panel simply disappeared.
On the server console it will show "Player [] Has Disconnected"
![image](https://user-images.githubusercontent.com/45941794/167238075-b6458da9-76ca-422f-8d2c-09e99bcd2cfa.png)
As shown in the picture.
I'm clueless about this problem, any ideas on how to solve it?

**Comment by ghost** [comment]
Could you confirm if you are running on latest current server version (v1.3.9) and latest current client version (Pre RTSE)?

If you are not, could you try to replicate this issue to see if it's persisting?

**Comment by Crockan** [comment]
I have re-experimented and the problem still exists, using the latest client and server.
The problem doesn't exist with a purely fresh game client, it's probably a conflict with another mod, I'll try to troubleshoot and report.

**Comment by Crockan** [comment]
It doesn't seem to be a mod that is causing the problem, but the mod's name.
For example, this one
[==========功能========== by ( σ'ω')σ](https://steamcommunity.com/sharedfiles/filedetails/?id=2138434400)
This is a mod with **no actual function**, just written in Chinese: functionality, for easy mod sorting, like a tag.
The problem appears as soon as I add this or any other mod with unconventional characters. Maybe it's some sort of coding issue?

**Comment by Damntry** [comment]
Chiming in to add that we had the same problem. Thanks to @Crockan we didnt have to spend much time trying to solve it.

In our case it happened because of [this mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2808842065), which is relatively well known, so this could happen to anyone.

**Comment by ghost** [comment]
Working on it on latest unstable version! Thanks for pointing it out
