### ISSUE TITLE
Error help

### ISSUE THREAD

**Issue by icetrojan** [TastyLollipop/OpenWorld#28]
![image](https://user-images.githubusercontent.com/34628856/169135057-fbbd58fe-1c91-4c70-9ea5-474728073aa7.png)

**Comment by ghost** [comment]
To enable "Core" or any of the two DLCs, download this file or extract the contents from your "Extras" folder inside the server as if they were mods: https://github.com/TastyLollipop/OpenWorld/raw/main/Core%20%26%20DLCs.zip
