### ISSUE TITLE
Core & Ideology disallowed

### ISSUE THREAD

**Issue by Jamesthe1** [TastyLollipop/OpenWorld#29]
Server Version: v1.3.9
Client Version: Pre RTSE

When joining my private server, among the list of disallowed mods, Core and Ideology are shown. I followed all steps to setup as they were described, with mods in the mods folder and client mods in whitelist.

Mod List:
[Multiplayer.txt](https://github.com/TastyLollipop/OpenWorld/files/8734181/Multiplayer.txt)

Logs:
[Log.txt](https://github.com/TastyLollipop/OpenWorld/files/8734162/Log.txt)

**Comment by ghost** [comment]
To enable "Core" or any of the two DLCs, download this file or extract the contents from your "Extras" folder inside the server as if they were mods: https://github.com/TastyLollipop/OpenWorld/raw/main/Core%20%26%20DLCs.zip
