### ISSUE TITLE
Issues connecting to the host

### ISSUE THREAD

**Issue by InterLooper-North** [TastyLollipop/OpenWorld#3]
I am attempting to setup a server, for a friend and I to test your mod on, but I am having difficulties actually getting the rimworld game to connect to the host. The 25555 port is open and i have gone into the settings text file and given it the devices local address. when i attempt to connect with rimworld i simply get the a text box saying the connection has timed out. any help would be nice. I am hesitant to upload screenshots because of the ips and such if you need any just ask.

**Comment by NirronCD** [comment]
make sure if the 25555 are open, use this site https://www.yougetsignal.com/tools/open-ports/, also you can screenshot ips if they're local not public, and check your firewall settings or anti-virus that can block connections.
EDIT: also can be that you local ip address of your machine changed for some reason

**Comment by ghost** [comment]
@NirronCD is correct. Also keep in mind the following:

If you are not even able to join locally, IE: using the local IP of the server to join, you might be wrongly configuring your server settings, that kind of connection should work no problem since It's local. Please check that the IP written in the server settings is the same as the local IP of the machine hosting

**Comment by InterLooper-North** [comment]
Once I am back from my tournament tomorrow I'll attempt to implement to changes and try a Lan connection

**Comment by InterLooper-North** [comment]
xfinity is stupid i got it figured out thx man

**Comment by InterLooper-North** [comment]
fuck y
![Capture](https://user-images.githubusercontent.com/100975396/156971045-1f42939e-35df-4b0b-be6e-819dc6f2f630.PNG)
a

**Comment by InterLooper-North** [comment]
that uploaded wrong but i think it captures my delieus state
