### ISSUE TITLE
Special characters (i.e. ampersands) in XML data cause mismatch issues

### ISSUE THREAD

**Issue by Jamesthe1** [TastyLollipop/OpenWorld#30]
Server Version: v1.3.9
Client Version: Pre RTSE

Special characters such as `&amp;`, `&quot;`, and `&lt;` cause mismatch issues between the client and the server, as the former correctly formats them while the latter does not appear to.

For example, the client will give the server:
`Chemicals & Neutroamine`
But the server will compare it against:
`Chemicals &amp; Neutroamine`
Thus creating a mismatch.

**Comment by ghost** [comment]
Fixed in current unstable version! Thanks for the feedback
