### ISSUE TITLE
[Suggestion] reload anytime setting

### ISSUE THREAD

**Issue by Brumes-Wolf** [TastyLollipop/OpenWorld#33]
First of, this mod is really cool and its really slick to setup.

I want to play this with a very small group of friends, so enforcing commitment mode to prevent cheating isn't needed in that situation.
There already seems to be a toggle for allowing dev mode, it would be great if a similar setting could be made to allow for save-scumming.

**Comment by ghost** [comment]
Hello there! It is planned to allow toggling commitment mode. However, for now the mod has quite a few functions that are directly attached to being on commitment mode due to awkward game code. It will be added when ready!
