### ISSUE TITLE
[Suggestion] Rename server file

### ISSUE THREAD

**Issue by Redstylt** [TastyLollipop/OpenWorld#35]
Hello,

Could you delete the space in your file's names ??
I would avoid this kind of command (and troubleshooting to figure out this)
All that we tried (after a day of work ^^) : 
```
mv "OpenWorldServer" OpenWorldServer
mv "Open World Server" OpenWorldServer
mv Open\ World\  Server OpenWorldServer 
mv Open\ World\  Server OpenWorldServer
```
To figure out this : 
`mv Open\ World\ Server openworldserver`

Thank you!

PS: Details matter 🥇

**Comment by Haukinger** [comment]
Also, underscores in namespaces are unusual, and they'd go away with the spaces (I'd rename the project files and solutions, too, accordingly)

**Comment by PreXentagon** [comment]
This should have been default, recommend changing build actions in order to make sure atleast the unix based builds have no spacings. 

having lots of issues with trying to get this project inside of a docker container for pterodactyl use due to them :(

**Comment by ghost** [comment]
On it! Thanks for the feedback
