### ISSUE TITLE
ARMX64_Selfcontained version

### ISSUE THREAD

**Issue by jakubraz** [TastyLollipop/OpenWorld#36]
Hello,

I have problem with running new version of the server, because I was running it on Raspberry Pi 4 - which is ARM64 based procesor so in version 1.3.9 it was running smoothly on ARM64_selcontained version but now I am not able to get this working. 

Will there be this version ?

Thank you so much for answer.

**Comment by ghost** [comment]
Hello there! I am aware that the ARM64 based version is missing for now. My visual studio recently got an update that is preventing me from exporting to that target since it is suposed to be still in experimental phase, will upload it when I get able to do so
