### ISSUE TITLE
Error while loading a map

### ISSUE THREAD

**Issue by waylenwasywas** [TastyLollipop/OpenWorld#44]
An error occurred while loading a map. See error log for more information.

This file was saved with a different set of mods active than those we are currently running. This may or may not cause problems, depending on exactly these mods do.

File was saved with (in this order):
None
We are currently running with (in this order):
Harmony, Core, Hugslib, Open World

I am running on a ubuntu 20.04 LTS server. I have all the mods loaded on both the client and server but it is not working. 
Rimworld version: 1.4
Other users are having the same issue.

**Comment by ghost** [comment]
Hello there! There are some issues that might be causing this problem, try the following:
- Ensure that players without a save are joining through a new game, not a existing one.
- Check that the saves are correctly named, if you recently updated or modified the server a different save name might be being requested, check the server settings for the name and then crossreference with the game saves

**Comment by LoringStar** [comment]
Hey waylenwasywas,

Try starting a solo game first. Then load or continue through the multiplayer button with the solo save and see if that fixes it. I had the same issue in the Rimworld 1.3 versions and that's how it was resolved. Make sure the world settings are the same as the solo game. Hope it works out.
