### ISSUE TITLE
Joining Existing Game Requests Password Twice 

### ISSUE THREAD

**Issue by William0216** [TastyLollipop/OpenWorld#50]
As title says, it requests password confirmation when joining a game that you already have an account on.

![temp Rimworld](https://user-images.githubusercontent.com/32989615/200199181-ac24c22c-1f66-4283-8da1-4d30de0fa921.png)

**Comment by ghost** [comment]
Not sure the thing you are trying to point out in this issue, that's the current way of login into the server

**Comment by William0216** [comment]
I'm pointing out that asking for password twice when joining, (not creating), an existing account is redundant. 

In other words, there only needs to be 1 password field for this. 

I understand asking for confirmation when you first join however this is still asking (for you to type the same password twice) after it has already been created. I would suggest removing the Confirm Password field on the join "Existing Game" menu.

This is the menu I am talking about:
![image](https://user-images.githubusercontent.com/32989615/201834969-cdbb50a5-2013-4d9c-9482-6e0ebe8e7ac5.png)

**Comment by ghost** [comment]
Got it! We are currently reorganizing the code from inside the mod to make it cleaner and more optimized, when we come across UI improvements I'll make sure this gets changed as well.
