### ISSUE TITLE
Broken Trade Quests

### ISSUE THREAD

**Issue by William0216** [TastyLollipop/OpenWorld#54]
I received a trade quest for a player settlement and did not have the option to fulfill it upon arrival
![image](https://user-images.githubusercontent.com/32989615/201235127-10928f30-b436-48de-bf6e-6670db79ed9e.png)
![image](https://user-images.githubusercontent.com/32989615/201235189-7aa37b37-5a0a-4114-b0d8-66bc7a580ff3.png)

**Comment by ghost** [comment]
Hello there, these quests are bugged at the current version of the mod. They will be removed completely in the near future. Still, thanks for reporting the issue.
