### ISSUE TITLE
How do I get a singleplayer save in the server?

### ISSUE THREAD

**Issue by BENTOdc** [TastyLollipop/OpenWorld#64]
I was playing with a friend on a server that he is hosting, but often he doesn't play the time I can, so I decided to play alone today, but I found that I can't put the save in his server and I don't know what to do, cause I made too much progress and I dind't wanted to lose this
Is there a way to take the progress I made offline and put on the server??

**Comment by D12-Dev** [comment]
Yes, it should be possible to convert your save to multiplayer. First you need to find the location of your current save that you want to convert and duplicate it (Just in case you loose the save). From there, you will have to rename the save to your player id which you can find by running the inspect command in the server console on your username, for example "inspect D12".  Next, you will need access to the server console and be able to upload files. You must also download a program that can convert zip to zipx as the saves in openworld are stored as a zipx (You can use https://filestar.com/download for this purpose). Next, zip up the save and convert it to zipx, once done you can then go ahead and upload it to the server under the folder saves and then you should be able to join on your current save.
