### ISSUE TITLE
MacOS RimWorld looks for save in wrong location

### ISSUE THREAD

**Issue by fe-ax** [TastyLollipop/OpenWorld#65]
Hi,

The MacOS version of the game/mod look at different save locations.

Game: `/Users/username/Library/Application Support/RimWorld/Saves`
Mod: `/Users/username/Library/Application Support/ludeon.rimworld/Saves`

It works flawlessly after symlinking the ludeon.rimworld to RimWorld like so:

```bash
cd /Users/username/Library/Application Support/;
rm -rf ludeon.rimworld;
ln -s RimWorld ludeon.rimworld;
```

I've posted this in the Discord channel too.

**Comment by saffue** [comment]
hey sorry, dont check here too often i did see in the discord and saved it to help others, thank you so much <3
