### ISSUE TITLE
Continuing a save file

### ISSUE THREAD

**Issue by InterLooper-North** [TastyLollipop/OpenWorld#7]
A friend and i were testing and we found what i think is an error.
![Capture](https://user-images.githubusercontent.com/100975396/157099110-92b43fa6-65fa-46d6-b787-03234ece4cbd.PNG)
Here we were attempting to figure how to reconnect and continue. We attempting using the load menu but that did not connect us to the server instead ran a local version of the save. When attempting to reconnect in the new colony menu the colony was predictively deleted and replaced. Is there a way to continue a save currently?

**Comment by ghost** [comment]
There is a button in the load menu to connect to the server with an existing save. At the bottom left of the page. Is it not present / working?

**Comment by InterLooper-North** [comment]
The person I has working with neglected to mention they did not use this. It worked as intended thankyou.
