### ISSUE TITLE
Private servers

### ISSUE THREAD

**Issue by pavlojs** [TastyLollipop/OpenWorld#8]
It will be possible in future to make private password protected servers? Just want to make a feature request.

**Comment by NirronCD** [comment]
as far i know, there's no way to put a password on the server, but you can always ban player that you don't like 
EDIT: this need to be heavily implemented

**Comment by NicholasEwing** [comment]
> It will be possible in future to make private password protected servers? Just want to make a feature request.

How can random people even find your server unless you're giving out the external IP / port?

**Comment by ghost** [comment]
> It will be possible in future to make private password protected servers? Just want to make a feature request.

Latest version contains a Whitelist function, allowing only certain players to join the server. I believe this is what you wanted, so I'm closing this issue for now!
